# Generated by Django 5.0.6 on 2024-05-14 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_registrationapproval'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationApproval',
        ),
    ]
