# Generated by Django 5.0.6 on 2024-05-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_pendingregistration_delete_registrationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='full_name',
            field=models.CharField(default='none', max_length=150),
            preserve_default=False,
        ),
    ]
