# Generated by Django 5.0.6 on 2024-05-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_pendingregistration_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='None', max_length=150),
            preserve_default=False,
        ),
    ]
