# Generated by Django 5.0.6 on 2024-05-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_special_access',
            field=models.BooleanField(default=False),
        ),
    ]
