# Generated by Django 5.0.6 on 2024-08-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_customuser_has_special_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
