# Generated by Django 5.0.6 on 2024-09-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_customuser_telegram_chat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendingregistration',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='last_name',
            field=models.CharField(default='test', max_length=150),
            preserve_default=False,
        ),
    ]
