# Generated by Django 5.0.6 on 2024-05-23 07:55

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bartime',
            name='datetime',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
