# Generated by Django 5.0.6 on 2024-05-26 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_created_at_remove_project_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='project',
            name='viewers',
        ),
    ]
