# Generated by Django 5.0.6 on 2024-07-08 19:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_responsible_person_alter_project_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deploy_team_members',
            field=models.ManyToManyField(blank=True, related_name='deploy_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='design_files',
            field=models.FileField(blank=True, null=True, upload_to='design_files/'),
        ),
        migrations.AddField(
            model_name='project',
            name='design_team_members',
            field=models.ManyToManyField(blank=True, related_name='design_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='domain_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='domain_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.CharField(blank=True, choices=[('wordpress', 'Wordpress'), ('technical', 'Technical'), ('seo', 'SEO'), ('digital_marketing', 'Digital Marketing')], max_length=50, null=True),
        ),
    ]
