# Generated by Django 5.0.6 on 2024-07-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_deploy_team_members_project_design_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='full_name',
            field=models.CharField(default='Mr', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
