# Generated by Django 5.0.6 on 2024-07-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_full_name_alter_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='host_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='host_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
