# Generated by Django 5.0.6 on 2024-07-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_host_end_date_project_host_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='phone_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
