# Generated by Django 5.0.6 on 2024-07-16 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('result', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('error', 'Error'), ('none', 'None')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='projects.project')),
            ],
        ),
    ]
