# Generated by Django 5.0.6 on 2024-08-26 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_smslog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='deploy_team_members',
        ),
        migrations.RemoveField(
            model_name='project',
            name='design_team_members',
        ),
        migrations.RemoveField(
            model_name='project',
            name='domain_start_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='host_start_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='project',
            name='team',
        ),
    ]
