# Generated by Django 5.0.6 on 2024-08-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_project_deploy_team_members_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='manager_full_name',
        ),
        migrations.AddField(
            model_name='project',
            name='project_name',
            field=models.CharField(default='test', max_length=150),
            preserve_default=False,
        ),
    ]
