# Generated by Django 5.0.6 on 2024-08-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_rename_name_project_manager_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contract_files',
            field=models.FileField(blank=True, null=True, upload_to='contract_files/'),
        ),
    ]
