# Generated by Django 5.0.6 on 2024-09-03 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_project_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='full_name',
        ),
    ]
