# Generated by Django 5.0.6 on 2024-10-15 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_remove_project_full_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('project_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('photo_frequency', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('videos_per_month', models.PositiveIntegerField()),
                ('photos_per_month', models.PositiveIntegerField()),
                ('organization_colors', models.TextField()),
                ('collaboration_duration', models.TextField()),
                ('contract_file', models.FileField(upload_to='contracts/')),
                ('damage', models.TextField()),
                ('consultation', models.BooleanField(default=False)),
                ('caption_writing', models.BooleanField(default=False)),
                ('cover_design', models.BooleanField(default=False)),
                ('post_scenario_writing', models.BooleanField(default=False)),
                ('teaser', models.BooleanField(default=False)),
                ('drone_shot', models.BooleanField(default=False)),
                ('outside_shoot', models.BooleanField(default=False)),
                ('out_of_city_shoot', models.BooleanField(default=False)),
                ('team_members', models.ManyToManyField(blank=True, related_name='content_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
