# Generated by Django 5.0.6 on 2024-10-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_contentproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentproject',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/'),
        ),
    ]
