# Generated by Django 5.0.6 on 2024-09-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workreport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workreport',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
