# Generated by Django 5.0.6 on 2024-10-12 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان جلسه')),
                ('meeting_date', models.DateTimeField(verbose_name='تاریخ جلسه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات جلسه')),
                ('records', models.TextField(blank=True, null=True, verbose_name='صورت جلسه')),
                ('participants', models.ManyToManyField(related_name='meetings', to=settings.AUTH_USER_MODEL, verbose_name='شرکت\u200cکنندگان')),
            ],
        ),
    ]
