# Generated by Django 5.0.6 on 2024-08-27 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_rename_is_completed_task_is_done_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubTask',
        ),
    ]
