# Generated by Django 5.0.6 on 2024-06-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_remove_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
