# Generated by Django 5.0.6 on 2024-08-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='file',
            field=models.FileField(upload_to='invoices/'),
        ),
    ]
