# Generated by Django 5.0.6 on 2024-05-25 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_ticket_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
