# Generated by Django 5.0.6 on 2024-05-26 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_rename_message_ticket_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketmessage',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticketmessage',
            name='user',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='TicketMessage',
        ),
    ]
